/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ransomdetection_RansomDetection */

#ifndef _Included_ransomdetection_RansomDetection
#define _Included_ransomdetection_RansomDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ransomdetection_RansomDetection
 * Method:    getEvents
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ransomdetection_RansomDetection_getEvents
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
